add check for adb and caution re git get
ruuvi/ruuvi.firmware.c pull request #212
Opened 2021-02-07 20:02 UTC by DG12

I know it's a kind of special test script but 
I added a test for adb (Android Debug Bridge) presence
and 
let user know that stiles will be wget ed from release

2021-02-07 20:04 UTC, DG12 reviewed
I tried to delete this tar from my repository but got a 404!

2021-02-08 14:09 UTC, ojousima requested changes

2021-02-08 14:09 UTC, ojousima commented on system_tests/test_sdk_dfu.sh
> +echo "          ${SDK_VARIANT}                      from github  OK?"
This check should be removed.

2021-02-08 14:10 UTC, ojousima commented
ok to test

2021-02-09 15:13 UTC, ojousima requested changes

2021-02-09 15:13 UTC, ojousima commented on system_tests/test_sdk_dfu.sh
> +pwd
This chunk should be removed, not only commented out

2021-02-10 10:17 UTC, ojousima approved these changes
Thanks, will merge once CI passes

2021-02-19 16:03 UTC, merged